FROM ozthekoder/chimpjs-xvfb

ENV HOME=/srv/package
WORKDIR ${HOME}
RUN echo ${google-chrome --version}
#COPY ./node_modules/ ${HOME}/node_modules/

# Copy the stuff which might change a bit more
COPY ./package.json ${HOME}/package.json

# Copy the stuff which we imagine may have changed - if we are doing a build
COPY ./chimp.config.js ${HOME}/chimp.config.js
COPY ./spec/ ${HOME}/spec/

CMD xvfb-run --server-args='-screen 0, 1024x768x16' chimp chimp.config.js --debug --log=verbose
